java.lang.RuntimeException: An error occured while executing doInBackground()
	at com.qihoo.jiagu.g.b.G.done(ko:5)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:384)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:251)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at com.qihoo.jiagu.g.b.h.run(gg:154)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.qihoo.jiagu.f.d.ALLATORIxDEMO(ak:776)
	at com.qihoo.jiagu.h.B.ALLATORIxDEMO(az:143)
	at com.qihoo.jiagu.h.B.ALLATORIxDEMO(az:136)
	at com.qihoo.jiagu.e.e.i.ALLATORIxDEMO(mp:248)
	at com.qihoo.jiagu.g.a.E.ALLATORIxDEMO(rh:233)
	at com.qihoo.jiagu.g.b.D.H(ko:366)
	at com.qihoo.jiagu.g.a.E.ALLATORIxDEMO(rh:320)
	at com.qihoo.jiagu.g.a.E.ALLATORIxDEMO(rh:153)
	at com.qihoo.jiagu.g.b.b.call(ko:313)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more
java.lang.NullPointerException
	at com.qihoo.jiagu.f.d.ALLATORIxDEMO(ak:776)
	at com.qihoo.jiagu.h.B.ALLATORIxDEMO(az:143)
	at com.qihoo.jiagu.h.B.ALLATORIxDEMO(az:136)
	at com.qihoo.jiagu.e.e.i.ALLATORIxDEMO(mp:248)
	at com.qihoo.jiagu.g.a.E.ALLATORIxDEMO(rh:233)
	at com.qihoo.jiagu.g.b.D.H(ko:366)
	at com.qihoo.jiagu.g.a.E.ALLATORIxDEMO(rh:320)
	at com.qihoo.jiagu.g.a.E.ALLATORIxDEMO(rh:153)
	at com.qihoo.jiagu.g.b.b.call(ko:313)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.qihoo.jiagu.g.b.h.run(gg:154)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
